### ISSUE TITLE
Deploy

### ISSUE THREAD

**Issue by iboss-ptk** [osmosis-labs/membrane#11]
## Deploy

The deployment process = `code => [build, optimize, store-code, instantiate]`, which can have multiple instantiation.
Assumption is, if they use this method, they will just use the same signer...

```sh
$ beaker deploy counter --signing-account test1 
$ beaker deploy counter --signing-account test1 
$ beaker deploy counter --signing-account test1 --no-rebuild
```

args:
```
contract_name,
raw
chain_id,
signer_args,
gas_args,
timeout_height,
label
```

## Assumptions
- shared gas params (2 txs, so actual gas limit is doubled) make it better in #14 
- shared signer params
- `chain_id` (change chain_id to network once working on #15 )

## Todo
- [x] use instantiate args & copy instanitate code
- [x] add store-code logic before instanitate
- [x] make building and optimizing default, add it to the logic before all
- [x] add flag `--no-rebuild` and impl the logic
